### ISSUE TITLE
Package should work only at user scope rather than project scope

### ISSUE THREAD

**Issue by laicasaane** [JoC0de/UnityVisualStudioSolutionGenerator#11]
Not everyone in my team uses the same development configuration, thus having this package works at the project scope would introduce conflicts across the team.

**Comment by JoC0de** [comment]
Hi @laicasaane,
thanks for the issue. I don't understand what correctly is the issue if not everyone uses it. Yes you need to install it project wide and the configuration is also stored at project level. But if someone e.g. uses VS Code instead of Visual Studio this extension shouldn't change anything. I didn't testet it explicitly but this extension just intercepts events that the Unity Visual Studio plugin produces and manipulates the output.
